name: Echo something
on: [push]
jobs:
    pippo: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        with:
            ref: refs/heads/master
        - name: Echo
          run: echo "Doveva anda cosi"
