name: Echo something
on: [push]
jobs:
    pippo: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
          with:
            ref: refs/heads/master
        - name: echo a sentence form a great driver
          run: echo "Doveva anda cosi"
